# Generated by Django 4.1 on 2024-02-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="fileupload", name="uname",),
    ]
