# Generated by Django 4.1 on 2024-02-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_fileupload_uname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email address"),
        ),
    ]
